### ISSUE TITLE
Error when incoming values are all without outliers

### ISSUE THREAD

**Issue by arachnida** [cpetry/node-red-contrib-cistern#2]
Hello,

I'm trying to use your node with a car sensor measuring the water level of a septic tank. This sensor gives quite often a spike value, your node does a good job filtering these out and giving a good median.

However if the 10 incoming values are all perfectly in range the node results in an error "Error filtering outliers. No value left!" and no median is calculated. I tested with an input node entering 10x the same value "2", the median should be 2 but the node gives an error. So if the values of my sensor are too good I can't use the node.

What is your opinion, is this a bug or supposed to be so?

**Comment by cpetry** [comment]
Oh this of course should not happen. Yes this is totally a bug. Interesting that I didn't see that before.

In case you can fix this yourself please create a pullRequest with unit test. Otherwise I'll see when I have the time for it.

**Comment by arachnida** [comment]
I’m not really what I would call a programmer, but I have some knowledge of it so I’ll try a pullRequest.Thanks for the very fast answer,arachnidaSent from my iPadOn 6 May 2023, at 10:46, cpetry ***@***.***> wrote:﻿
Oh this of course should not happen. Yes this is totally a bug. Interesting that I didn't see that before.
In case you can fix this yourself please create a pullRequest with unit test. Otherwise I'll see when I have the time for it.

**Comment by cpetry** [comment]
I just found some time to look at the problem.
Just released/published the new 1.0.8 node version.

Can you please check if this fixes your issue?

**Comment by arachnida** [comment]
Mmm, 1.0.8 doesn't show up in my palette, latest stays at 1.0.7.

**Comment by cpetry** [comment]
You are right! I had to update manually on node red. Now 1.0.8 is available

**Comment by arachnida** [comment]
Great, seems to work now! I only tested with a batch of numbers, no arrays. The error only shows up now when I use GET outliers and there is no outlier during the 10 samples, so this is correct. Thanks for the fast response and fix, appreciated!

**Comment by cpetry** [comment]
Great!
Thanks for your feedback 🙂.
Feel free to add more bug reports or suggestions.
